# Generated by Django 4.2.11 on 2024-03-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(choices=[('fisica', 'Fisica'), ('juridica', 'Juridica')], max_length=8)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255)),
                ('obs', models.TextField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=255)),
                ('os', models.CharField(blank=True, max_length=8)),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('docto', models.CharField(blank=True, max_length=15, null=True)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('gtinOuEan', models.CharField(blank=True, max_length=20)),
                ('ncm', models.CharField(blank=True, max_length=20)),
                ('extipi', models.CharField(blank=True, max_length=20)),
                ('cest', models.CharField(blank=True, max_length=20)),
                ('palchav', models.CharField(blank=True, max_length=30)),
                ('empresa', models.CharField(max_length=255)),
                ('un', models.CharField(blank=True, choices=[('un', 'UN'), ('pc', 'PC'), ('cx', 'CX'), ('dz', 'DZ'), ('cj', 'CJ'), ('mt', 'MT'), ('m2', 'M2'), ('kg', 'KG'), ('frd', 'FRD')], max_length=3)),
                ('icms', models.CharField(blank=True, max_length=255)),
                ('ipi', models.CharField(blank=True, max_length=255)),
                ('cofins', models.CharField(blank=True, max_length=255)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('valorUn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lote', models.CharField(blank=True, max_length=8)),
                ('codProd', models.CharField(blank=True, max_length=20)),
                ('qtde', models.IntegerField()),
                ('qtde_tot', models.IntegerField(blank=True)),
            ],
        ),
    ]
