# Generated by Django 4.2.11 on 2024-04-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=1, verbose_name='estoque atual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveBigIntegerField(default=0, verbose_name='estoque minimo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='importado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='produto',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, max_length=8, verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valorUn',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='valor unitário'),
        ),
    ]
