# Generated by Django 4.2.11 on 2024-04-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_descricao_produto_estoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='importado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtde_tot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
