# Generated by Django 4.2.11 on 2024-04-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_importado_alter_produto_qtde_tot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('produto',)},
        ),
        migrations.AlterField(
            model_name='produto',
            name='codProd',
            field=models.CharField(blank=True, max_length=20, verbose_name='código do produto'),
        ),
    ]
