# Generated by Django 4.2.11 on 2024-04-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_options_alter_produto_codprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cest',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='extipi',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='gtinOuEan',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ncm',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='palchav',
        ),
    ]
