# Generated by Django 5.0.4 on 2024-05-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_produto_cest_remove_produto_extipi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
