# Generated by Django 5.0.4 on 2024-05-19 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cliente',
        ),
    ]
