# Generated by Django 5.0.4 on 2024-05-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_remove_produto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pessoa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
