# Generated by Django 5.0.4 on 2024-05-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_produto_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='estoque minimo'),
        ),
    ]
