# Generated by Django 5.0.4 on 2024-05-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_produto_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='qtde',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
