# Generated by Django 5.0.4 on 2024-05-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_produto_qtde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='importado',
            field=models.BooleanField(),
        ),
    ]
