# Generated by Django 5.0.4 on 2024-05-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_alter_produto_importado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='importado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
