# Generated by Django 4.2.11 on 2024-03-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('dt_real', models.DateField()),
                ('dt_conc', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('favorecido', models.CharField(max_length=255)),
                ('os', models.CharField(blank=True, max_length=8)),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('conta', models.CharField(blank=True, max_length=15, null=True)),
                ('doctos', models.CharField(blank=True, max_length=15, null=True)),
                ('empresaDespesa', models.CharField(max_length=255)),
                ('banco', models.CharField(blank=True, max_length=255)),
                ('caixa', models.CharField(blank=True, max_length=255)),
                ('done', models.CharField(blank=True, choices=[('doing', 'Doing'), ('done', 'Done')], max_length=5)),
            ],
        ),
    ]
