# Generated by Django 4.2.11 on 2024-03-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recebimentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recebimento',
            old_name='empresaDespesa',
            new_name='empresa',
        ),
    ]
