# Generated by Django 4.2.11 on 2024-03-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recebimentos', '0002_rename_empresadespesa_recebimento_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recebimento',
            old_name='favorecido',
            new_name='remetente',
        ),
    ]
