# Generated by Django 5.0.4 on 2024-05-16 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('produtos', '0005_remove_produto_cest_remove_produto_extipi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreçoVenda',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('descricao', models.CharField(max_length=255)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
            bases=('core.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='PreçoVendaIten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('valorUn', models.PositiveIntegerField(blank=True, null=True)),
                ('valorUnit', models.PositiveIntegerField(blank=True, null=True)),
                ('descontos', models.PositiveIntegerField(blank=True, null=True)),
                ('percentual_imposto', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_imposto', models.IntegerField(blank=True, null=True)),
                ('fretes', models.FloatField(blank=True, null=True)),
                ('seguros', models.PositiveIntegerField(blank=True, null=True)),
                ('subsTrib', models.PositiveIntegerField(blank=True, null=True)),
                ('outrosCustos', models.PositiveIntegerField(blank=True, null=True)),
                ('custoTotal', models.FloatField(blank=True, null=True)),
                ('preçoVendaTotal', models.FloatField(blank=True, null=True)),
                ('preçoVenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preçoVenda', to='preçoVendas.preçovenda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
