# Generated by Django 5.0.4 on 2024-05-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preçoVendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preçovendaiten',
            name='valorUn',
        ),
    ]
