# Generated by Django 5.0.4 on 2024-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preçoVendas', '0002_remove_preçovendaiten_valorun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preçovendaiten',
            name='valor_imposto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
