# Generated by Django 4.1.13 on 2024-03-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(choices=[('fisica', 'Fisica'), ('juridica', 'Juridica')], max_length=8)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('telCelular', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular')),
                ('telFixo', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone fixo')),
                ('empresaCliente', models.CharField(max_length=255)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('dt_enc', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
