# Generated by Django 4.2.11 on 2024-03-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='empresaCliente',
            new_name='empresa',
        ),
    ]
