# Generated by Django 4.2.11 on 2024-04-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='numero',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
