# Generated by Django 4.2.11 on 2024-03-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('dt_real', models.DateField()),
                ('dt_conc', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=8)),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('conta', models.CharField(blank=True, max_length=15, null=True)),
                ('doctos', models.CharField(blank=True, max_length=15, null=True)),
                ('empresa', models.CharField(max_length=255)),
                ('banco', models.CharField(blank=True, max_length=255)),
                ('caixa', models.CharField(blank=True, max_length=255)),
                ('done', models.CharField(blank=True, choices=[('doing', 'Doing'), ('done', 'Done')], max_length=5)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor')),
            ],
        ),
    ]
