# Generated by Django 4.2.11 on 2024-03-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='concialiado',
            field=models.CharField(blank=True, choices=[('doing', 'Doing'), ('done', 'Done')], max_length=5),
        ),
    ]
